# Generated by Django 5.2.13 on 2026-04-29 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=32, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('titulo', models.CharField(blank=True, default='', max_length=500)),
                ('descricao', models.TextField(blank=True, default='')),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('feed_url', models.URLField(blank=True, default='')),
                ('impacto', models.CharField(blank=True, default='pendente', max_length=32)),
                ('raw_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-publicado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=255)),
                ('ativos', models.ManyToManyField(blank=True, related_name='carteiras', to='core.ativo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carteira', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.ativo')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.noticia')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'noticia', 'ativo'), name='unique_alerta_por_usuario_noticia_ativo')],
            },
        ),
    ]
