# Generated by Django 5.2.13 on 2026-05-28 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_noticia_summary_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteRSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('nome', models.CharField(blank=True, default='', max_length=255)),
                ('confiabilidade', models.FloatField(default=0.5)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InteracaoNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abriu', models.BooleanField(default=False)),
                ('ignorou', models.BooleanField(default=False)),
                ('tempo_leitura', models.PositiveIntegerField(default=0)),
                ('origem', models.CharField(blank=True, default='', max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaClassificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentimento', models.CharField(choices=[('positivo', 'Positivo'), ('neutro', 'Neutro'), ('negativo', 'Negativo')], default='neutro', max_length=16)),
                ('impacto', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('baixo', 'Baixo'), ('indefinido', 'Indefinido')], default='indefinido', max_length=16)),
                ('urgencia', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baixa', 'Baixa'), ('indefinida', 'Indefinida')], default='indefinida', max_length=16)),
                ('setor', models.CharField(blank=True, default='', max_length=64)),
                ('tipo_evento', models.CharField(blank=True, default='', max_length=64)),
                ('tickers_relacionados', models.JSONField(blank=True, default=list)),
                ('relevancia_llm', models.FloatField(default=0.0)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('fallback', 'Fallback'), ('error', 'Error')], default='ok', max_length=16)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_final', models.FloatField(default=0.0)),
                ('prioridade', models.CharField(choices=[('critica', 'Critica'), ('alta', 'Alta'), ('media', 'Media'), ('baixa', 'Baixa')], default='media', max_length=16)),
                ('motivos', models.JSONField(blank=True, default=dict)),
                ('calculado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-calculado_em'],
            },
        ),
        migrations.CreateModel(
            name='PerfilInvestidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_risco', models.CharField(choices=[('conservador', 'Conservador'), ('moderado', 'Moderado'), ('agressivo', 'Agressivo')], default='moderado', max_length=32)),
                ('horizonte', models.CharField(choices=[('curto', 'Curto'), ('medio', 'Medio'), ('longo', 'Longo')], default='medio', max_length=32)),
                ('setores_preferidos', models.JSONField(blank=True, default=list)),
                ('sensibilidade_negativo', models.FloatField(default=0.5)),
                ('frequencia_alertas', models.CharField(choices=[('imediato', 'Imediato'), ('diario', 'Diario'), ('semanal', 'Semanal')], default='imediato', max_length=32)),
            ],
            options={
                'ordering': ['usuario_id'],
            },
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['publicado_em'], name='core_notici_publica_91bdce_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['impacto'], name='core_notici_impacto_28ebd7_idx'),
        ),
        migrations.AddField(
            model_name='interacaonoticia',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='core.noticia'),
        ),
        migrations.AddField(
            model_name='interacaonoticia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes_noticia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticiaclassificacao',
            name='noticia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classificacao', to='core.noticia'),
        ),
        migrations.AddField(
            model_name='noticiascore',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.noticia'),
        ),
        migrations.AddField(
            model_name='noticiascore',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticia_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilinvestidor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_investidor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='noticiascore',
            index=models.Index(fields=['prioridade'], name='core_notici_priorid_e6793b_idx'),
        ),
        migrations.AddIndex(
            model_name='noticiascore',
            index=models.Index(fields=['score_final'], name='core_notici_score_f_f23df0_idx'),
        ),
        migrations.AddConstraint(
            model_name='noticiascore',
            constraint=models.UniqueConstraint(fields=('noticia', 'usuario'), name='unique_score_por_usuario_noticia'),
        ),
    ]
