# Generated by Django 5.2.13 on 2026-05-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fonterss_interacaonoticia_noticiaclassificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilinvestidor',
            name='alerta_min_prioridade',
            field=models.CharField(choices=[('critica', 'Critica'), ('alta', 'Alta'), ('media', 'Media'), ('baixa', 'Baixa')], default='media', max_length=16),
        ),
    ]
