# Generated by Django 5.2.13 on 2026-06-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilinvestidor_alerta_min_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
