# Generated by Django 5.2.13 on 2026-06-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_noticia_confianca_fase4_noticia_explicacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='confianca_fase4',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='explicacao',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='provider_fase4',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='tickers_encontrados',
        ),
        migrations.AddField(
            model_name='noticiaclassificacao',
            name='confianca_fase4',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='noticiaclassificacao',
            name='explicacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='noticiaclassificacao',
            name='provider_fase4',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='noticiaclassificacao',
            name='tickers_encontrados',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
