# Generated by Django 5.2.13 on 2026-06-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_create_admin_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilinvestidor',
            name='notificacao_dashboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilinvestidor',
            name='notificacao_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilinvestidor',
            name='notificacao_push',
            field=models.BooleanField(default=True),
        ),
    ]
