# Generated by Django 5.2.13 on 2026-06-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_perfilinvestidor_notificacao_dashboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='relevancia_binaria',
            field=models.BooleanField(default=False),
        ),
    ]
