# Generated by Django 5.2.13 on 2026-06-23 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_consolidar_alertas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alerta',
            name='unique_alerta_por_usuario_noticia_ativo',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='ativo',
        ),
        migrations.AddField(
            model_name='alerta',
            name='ativos',
            field=models.ManyToManyField(related_name='alertas', to='core.ativo'),
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.UniqueConstraint(fields=('usuario', 'noticia'), name='unique_alerta_por_usuario_noticia'),
        ),
    ]
